line-length = 88
indent-width = 4

target-version = "py312"

[lint]
select = ["ALL"]

# C420: Slower dict.fromkeys
# COM812: Trailing Comma (Only covers single line trailing commas, seems out of place)
# D: Doc style
# EM: Error messages
# FBT: Boolean Trap (Slower)
# FIX002: Resolve TODO
# N802: Uppercase function names
# PLR0913: Too many args
# PTH: Use Pathlib (Wants slower API used)
# S101: Assert
# SLF001: Private member access
# TD002: TODO author
# TD003: TODO issue link
# TRY003: Avoid specifying long messages outside the exception class (Slower and less clear)
ignore = ["C420", "COM812", "D", "EM", "FBT", "FIX002", "N802", "PLR0913", "PTH", "S101", "SLF001", "TD002", "TD003", "TRY003"]

[lint.extend-per-file-ignores]

# ANN201: Missing return type
# PLR2004: Magic Numbers
# S101: Assert
"tests/*" = ["ANN201", "PLR2004", "S101"]

[format]
quote-style = "double"
indent-style = "space"
