name: Tag And Release

on:
  workflow_dispatch:
    inputs:
      body:
        type: string
        description: "Info on what changed in the release"
        required: false

jobs:
  tag-and-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Get Version
        id: version
        run: |
            version=$(grep version pyproject.toml | grep -Eo [0-9]+(.[0-9])+)
            if [ -z $version ]; then
            echo "Failed to parse version from pyproject.toml"
            exit 1
            fi
            echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.version.outputs.version }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" --latest \
            --title="$tag" --fail-on-no-commits
