name: Tag And Release

on:
  workflow_dispatch:
    inputs:
      body:
        type: string
        description: "Info on what changed in the release"
        required: true

jobs:
  tag-and-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Get Version
        id: version
        run: |
            version=$(grep version pyproject.toml | grep -Eo [0-9]+(.[0-9])+)
            if [ -z $version ]; then
            echo "Failed to parse version from pyproject.toml"
            exit 1
            fi
            echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
